### ISSUE TITLE
Doesn't work with tabs

### ISSUE THREAD

**Issue by idbrii** [coderifous/textobj-word-column.vim#1]
Great plugin! I love the idea, but unfortunately it doesn't work with tabs. Looks like it's because when using `|` to jump to a column, it uses screen columns (instead of actual columns -- see `:help bar`). Maybe you could multiply the number of tab characters by the value of `tabstop`?

Repro:
Edit word-column.vim
Put cursor on first 'let' in file.
`vic` selects all of the lets.
`%sm/^  /\t` to switch to tabs.
Put cursor on first 'let' in file.
`vic` selects some weird stuff (on ca711dd it selects a bunch of stuff late in the file and on 69c30da it selects from the beginning of the line).

**Comment by coderifous** [comment]
Thanks for the report, I'm looking into it now.

**Comment by coderifous** [comment]
Pydave, thanks for reporting this.  This should be fixed now, please report any other issues.
