### ISSUE TITLE
Select based on word under cursor?

### ISSUE THREAD

**Issue by idbrii** [coderifous/textobj-word-column.vim#3]
(Using ea8ff3d.)

Given this text:

```
let g:ctrlp_extensions = ['funky', 'register']
nmap <C-o>l :CtrlPLastMode<CR>
nmap <C-o>b :CtrlPBuffer<CR>
nmap <C-o>f :call ctrlp#init(ctrlp#funky#id())<CR>
nmap <C-o>r :CtrlPRegister<CR>
```

If I put my cursor on the first `<` and type `vic`, then the `:` and the column of `<` beneath it are selected. But what I wanted was just the column of `<`.
I would expect `viC` to do what I want, but instead it selects `g:ctrlp_extensions` and all of the lines below it. I'm not certain if that's correct. Maybe that's related to #1.

Is there any way to do what I want? `vaC` does the same thing as `viC` in this case. `vac` selects `g:` and the lines below it. It seems like I want the selection priority to be on the word that my cursor is on.

**Comment by coderifous** [comment]
I'm going to try to get to this sometime this week.

**Comment by coderifous** [comment]
pydave - I'm not sure of the best solution to this one.  I could make the plugin more aggressive in it's identification of columns, such that it peeks around for three nearest identical column members, and if it finds them, then it decides that the column should only include identical members.  That would solve the scenario you had, but consider code like this:

``` vimscript
nmap <C-o>l :CtrlPLastMode<CR>
nmap <C-o>b :CtrlPBuffer<CR>
nmap <C-o>f :call ctrlp#init(ctrlp#funky#id())<CR>
imap <C-o>r :CtrlPRegister<CR>
imap <C-o>r :CtrlPRegister<CR>
imap <C-o>r :CtrlPRegister<CR>
```

If your cursor were on either `nmap` or `imap`, and you typed `vic`, then only half of the probably-desired column would be selected.  My described approach would probably create as many problems as it solved.

A more sophisticated line-pattern analysis could be done on each line.  Perhaps each line could be parsed to identify word-start locations, and a pattern of columns could be identified using that.  For instance, the desired lines in your scenario each have word-starts at columns 1, 6, and 13.  Perhaps an algorithm could do something with that.

I may proceed with a some experimental approaches and then try living with them for a while.  If I do so, I'll push them up as branches and you are welcome to use them and provide feedback on whether they are improvements or not.

**Comment by idbrii** [comment]
I guess I expect it to act like `viw` to select the width and then match starting word boundaries to determine the above and below rows to select. It would only look at end of word boundaries when the cursor is in column 1 (otherwise all nonblank lines in the file would match).

Then, what would be really cool is if after you started the selection, when you typed `ip` again, it would expand the selection to the end of the longest word in the column. (Similar to how `vapap` will expand to select surrounding paragraphs.) Adding this expansion would allow it to work in situations like your example screencast when the cursor is not on the longest word in the column.

**Comment by jdanbrown** [comment]
+1 for repeated ipipip. That'd be a nice vim idiom to support.

**Comment by idbrii** [comment]
I think I meant `ic` and not `ip` (repeated use of the textobj-word-column map).

**Comment by idbrii** [comment]
Forgot to mention that I've implemented this [in my fork](https://github.com/idbrii/textobj-word-column.vim). I believe it was part of my "more-exact-matches" branch ~ d6b346a2e2cebae52fc7d6745cd6844dacdf20f6.

That resolves my issue.
