### ISSUE TITLE
E132 on large text selections: too much recursion

### ISSUE THREAD

**Issue by idbrii** [coderifous/textobj-word-column.vim#4]
s:find_boundary_row is recursive and can cause `E132: Function call depth is higher than 'maxfuncdepth'` on selections using more than `&maxfuncdepth` lines. (maxfuncdepth defaults to 100) Looks like function could be done iteratively instead.

Also, not really relevant to this issue, but have you seen [textobj-user](http://www.vim.org/scripts/script.php?script_id=2100)? Might be useful to take care of some boilerplate stuff?

**Comment by coderifous** [comment]
Hey pydave - This bit me the other day too.  I liked the recursive solution, but unless we have tail-recurcsion it's not viable.  I'll switch to iteration.

On the topic of textobj-user, I took a quick look at it - it looks like it's handy if the textobj's can be defined in terms of regexes, which these textobjects aren't.
